version: '3.8'
services:
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
  frontend:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
